services:
  # Dịch vụ cho môi trường Phát triển (Development)
  fe_dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      # Cổng host:Cổng container
      - "${VITE_FE_PORT}:5173" # Ánh xạ VITE_FE_PORT của host đến cổng 5173 của container (Vite dev server)
    environment:
      NODE_ENV: development
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    command: npm run dev
    env_file:
      - .env

  # Dịch vụ cho môi trường Production (Sản phẩm)
  fe_prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      # Cổng host:Cổng container
      - "${VITE_FE_PORT}:80" # Ánh xạ VITE_FE_PORT của host đến cổng 80 của container (Nginx)
    env_file:
      - .env
    # Không có 'depends_on' vì backend không nằm trong cùng compose file