services:
  mysql:
    image: mysql:8.0
    container_name: mysql-sti
    environment:
      MYSQL_ROOT_PASSWORD: sti@1234
      MYSQL_DATABASE: sti_mes_2025_dev
      MYSQL_USER: sti
      MYSQL_PASSWORD: sti@1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - app-network
    healthcheck: # Health check mới cho MySQL
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psti@1234"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s # Cho MySQL thời gian khởi động

  mongodb:
    image: mongo:latest
    container_name: myts-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      TZ: Asia/Ho_Chi_Minh
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "sh", "-c", "echo 'db.runCommand(\"ping\").ok' | mongosh mongodb:27017/iot_gateway --quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  dbgate:
    image: dbgate/dbgate:latest
    container_name: myts-dbgate
    ports:
      - "3001:3000"
    environment:
      DG_AUTH_ENABLED: "false"
    networks:
      - app-network
    depends_on:
      mongodb:
        condition: service_healthy

  emqx:
    image: emqx/emqx:latest # Sử dụng image EMQX thông thường
    container_name: emqx_node
    ports:
      - "1883:1883"      # MQTT port
      - "8083:8083"      # MQTT over WebSocket
      - "8084:8084"      # MQTT over SSL/TLS
      - "8883:8883"      # MQTT over SSL/TLS
      - "18083:18083"    # Dashboard/Management API
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_etc:/opt/emqx/etc
      - emqx_log:/opt/emqx/log
    environment:
      EMQX_NAME: emqx
      EMQX_HOST: emqx_node
      TZ: Asia/Ho_Chi_Minh
    networks:
      - app-network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:18083/api/v5/brokers || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 120s # Giữ thời gian khởi động dài để EMQX ổn định

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-sti
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - mysql
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile # Trỏ đến Dockerfile của backend
    container_name: myts-backend
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy # Backend sẽ chờ MySQL healthy
      mongodb:
        condition: service_healthy # Backend sẽ chờ MongoDB healthy
      emqx:
        condition: service_healthy # Backend sẽ chờ EMQX healthy
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  mysql_data:
  emqx_data:
  emqx_etc:
  emqx_log: